keep-starknet-strange/satoru

src/lib.cairo, src/utils/arrays.cairo, tests/utils/test_arrays.cairo
=>  Feat: Implement the functions of Array contract

.github/workflows/security.yml
Implemented Caracal which is a static analyzer.
The issue:
#28 
- Feature
Caracal is going to get launched after each PR or merge to main and it will create an artificat with the static analyzer data which will get saved.
No
No
=> Implemented caracal in the CI

src/nonce/nonce_utils.cairo, src/utils/hash.cairo, tests/data/test_data_store.cairo, tests/nonce/test_nonce_utils.cairo
- Feature
Resolves: #249
As discussed in the telegram group, this PR prefers propagating `Result`s instead of unwrapping them.
=> Feat: Implement the functions in the `NonceUtils` library

src/exchange/error.cairo, src/exchange/exchange_utils.cairo
- Feature
Resolves: #267
Missing test because of the following error, changing the function interface or creating a wrapper contract just for this seems inappropriate.
=> Feat: Implement the function in the `exchange_utils` library.

.github/workflows/book.yml
Implemented a tmp solution for the book, so nothing happens if the book didnt change
- Bugfix
- It is gonna check if the book directory has any change if not nothing will happen
=> Added a tmp solution for the book

src/event/event_emitter.cairo, src/fee/fee_utils.cairo, tests/fee/test_fee_utils.cairo
[](https://github.com/keep-starknet-strange/satoru/issues/265)
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
=> feat: Fee utils

src/lib.cairo, src/tests_lib.cairo, src/utils/global_reentrancy_guard.cairo, tests/data/test_data_store.cairo, tests/feature/test_feature_utils.cairo, tests/nonce/test_nonce_utils.cairo, tests/utils/test_reentrancy_guard.cairo
Lots of repetition in tests regarding setup of stores.
Resolves: #NA
Moved setup code to `src/test_lib.cairo`.
Also enforces usage of safe dispatcher.
=> Refactor redundant test setups

book/src/smart-contracts-architecture/deposit-module.md, book/src/smart-contracts-architecture/exchange-module copy.md, src/event/event_emitter.cairo
- Feature
Deposit event emitters missing
Resolves: #NA
- Added Deposit event emitters
No
=> implemented deposit event emitter functions

src/event/event_emitter.cairo
[#296 
](https://github.com/keep-starknet-strange/satoru/issues/296)# Pull Request type
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
I didn't implemented tests for this PR because actually all does only event emitting.
=> feat: order events

src/utils/basic_multicall.cairo, src/utils/error.cairo, tests/utils/test_basic_multicall.cairo
- Feature
Resolves: https://github.com/keep-starknet-strange/satoru/issues/238
- Implement multicall function under utils/basic_multicall.cairo
- Usage if Call struct from starknet::account
- Usage of call_contract_syscall
No
=> Feat: multicall

book/src/smart-contracts-architecture/oracle-module.md, book/src/smart-contracts-architecture/order-module.md, src/lib.cairo, src/order/base_order_utils.cairo, src/order/decrease_order_utils.cairo
Created the signature for the library decrease_order_utils so the contributors can work on the next issue.
=> Added the signature for the decrease_order_utils + book.

book/src/smart-contracts-architecture/order-module.md, src/lib.cairo, src/order/decrease_order_utils.cairo, src/order/increase_order_utils.cairo
Created the signature for the library increase_order_utils so the contributors can work on the next issue.
=> Added the signature for the increase_order_utils + book.

src/tests_lib.cairo, tests/callback/test_callback_utils.cairo, tests/event/test_order_events_emitted.cairo, tests/event/test_position_events_emitted.cairo, tests/event/test_referral_events_emitted.cairo, tests/event/test_withdrawal_events_emitted.cairo
- Testing
Resolves: https://github.com/keep-starknet-strange/satoru/issues/318
- Test implemented for PositionEvent
No
Reactoring to include setup_evetn_emitter in test_lib.cairo.
=> Test:PostionEvents

src/nonce/nonce_utils.cairo, tests/nonce/test_nonce_utils.cairo
- Bugfix
Resolves: #347
Should make nonce tests more deterministic
=> fix: unstable nonce test

Scarb.toml
Some scarb dependencies were not pinned to a commit or release version so it could bring some unpredictable changes.
Added rev on dependencies where it was missing.
=> feat: add scarb rev

src/role/role_module.cairo
- Feature
Role module is not initializable
Resolves: #NA
Made role module initializable since it's herited by other contracts
=> feat: initializable role module

src/role/role_module.cairo, tests/role/test_role_module.cairo
role module was in camel case
Refactored role module into snake case
=> refactor: convert role_module functions to snake_case

src/swap/swap_handler.cairo, tests/swap/test_swap_handler.cairo
Implemented the swap function in the swap_handler contract
=> Feat/swap_handler: Implemented the swap function in the swap_handler contract

src/fee/error.cairo, src/fee/fee_handler.cairo, tests/fee/test_fee_handler.cairo
https://github.com/keep-starknet-strange/satoru/issues/311
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
=> Feat fee handler impl

src/router/router.cairo, tests/router/test_router.cairo
- Feature
Resolves: https://github.com/keep-starknet-strange/satoru/issues/252
No
=> feat: Implement the `plugin_transfer` function

src/lib.cairo, src/utils/span32.cairo, src/withdrawal/withdrawal.cairo, tests/data/test_withdrawal.cairo, tests/event/test_withdrawal_events_emitted.cairo
Span32 struct with a max size of 32
- Feature
Resolves: #305
=> feat: implement Span32 struct

tests/role/test_role_module.cairo, tests/router/test_router.cairo, tests/utils/test_starknet_utils.cairo
New PR have been including SafeDispatcher ,
corrected it with Dispatcher and matching the return not being an option
WL : 30 min
=> Bug dispatcher 2

src/deposit/deposit.cairo, src/event/event_emitter.cairo, tests/event/test_adl_events_emitted.cairo, tests/event/test_callback_events_emitted.cairo, tests/event/test_config_events_emitted.cairo, tests/event/test_gas_events_emitted.cairo, tests/event/test_market_events_emitted.cairo, tests/event/test_oracle_events_emitted.cairo, tests/event/test_order_events_emitted.cairo, tests/event/test_position_events_emitted.cairo, tests/event/test_pricing_events_emitted.cairo, tests/event/test_referral_events_emitted.cairo, tests/event/test_swap_events_emitted.cairo, tests/event/test_timelock_events_emitted.cairo, tests/event/test_withdrawal_events_emitted.cairo
Add all missing tests from GMX repo
Refactor all u256 into u128 in tests and event_emitter.cairo
Resolves: #NA  
-
-
-
Yes, updated Deposit struct and used u128 instead of u256
N/A
=> Feat: add all missing events with tests

.all-contributorsrc
👥 Add Zizou and Darlington02as a contributor
=> 👥 Add Zizou and Darlington02as a contributor

src/pricing/swap_pricing_utils.cairo
Deleted 2 unused function (they are used in the emitter)
=> Deleted 2 unused function

tests/data/test_position.cairo
- Testing
Not overriding position store
Resolves: #NA
- successfully overriding position store
No
=> fixed position test override

src/exchange/withdrawal_handler.cairo, src/withdrawal/withdrawal_utils.cairo, tests/exchange/test_withdrawal_handler.cairo
https://github.com/keep-starknet-strange/satoru/issues/309
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
=> feat: withdrawal handler

.github/workflows/test.yml, tests/order/test_order.cairo
Update foundry to latest version 0.6.0
=> CI: update foundry version to 0.6.0

src/data/data_store.cairo, src/deposit/deposit.cairo, src/deposit/error.cairo, src/event/event_emitter.cairo, src/lib.cairo, tests/data/test_deposit_store.cairo, tests/event/test_callback_events_emitted.cairo
Implemented the deposit function in the datastore and I added some tests.
- Feature
Resolves: #283
-
-
-
No
=> Deposit functions in the DataStore

Scarb.toml, src/event/event_emitter.cairo, src/exchange/adl_handler.cairo, src/exchange/withdrawal_handler.cairo, src/lib.cairo, src/oracle/error.cairo, src/oracle/oracle.cairo, src/oracle/oracle_store.cairo, src/oracle/oracle_utils.cairo, src/oracle/price_feed.cairo, src/price/price.cairo, src/utils/arrays.cairo, src/utils/precision.cairo, src/utils/u128_mask.cairo, tests/oracle/test_oracle.cairo, tests/utils/test_arrays.cairo
=> Feat: Implemented oracle functions

.all-contributorsrc, README.md
=> doc: add betacod as contributor

src/lib.cairo, src/order/base_order_utils.cairo, src/tests/utils/test_i128.cairo, src/utils/i128.cairo
=> refactor: add i128 functions in utils

src/reader/reader_pricing_utils.cairo
Refactoring (no functional changes, no API changes)
We replaced by the correct max for u128
no
=> fix u128 max

.all-contributorsrc, README.md
Addition of two contributors (#420 and #421)
=> add contributors

src/utils/store_arrays.cairo
Closes #294
-[x] Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
=> fix: array store

src/data/data_store.cairo, src/lib.cairo, src/market/market_utils.cairo, src/position/position_utils.cairo, src/reader/reader.cairo, src/reader/reader_pricing_utils.cairo, src/tests/reader/test_reader.cairo
- Feature
- Testing
- implemented reader library
- Tests not completed because of the missing libraries
Resolves: #428
=> Feat: Implement the function in the reader contract

src/deposit/deposit_utils.cairo, src/gas/error.cairo, src/gas/gas_utils.cairo, src/tests/deposit/test_deposit_utils.cairo
Implementation of the functions in the gas_utils library
- Feature
Not currently implemented
Resolves: #422 
Implemented
No
=> feat: gas utils implementation

src/lib.cairo, src/market/market_utils.cairo, src/position/decrease_position_utils.cairo, src/position/error.cairo, src/position/position_utils.cairo, src/pricing/position_pricing_utils.cairo, src/tests/position/test_decrease_position_utils.cairo, src/tests_lib.cairo
Resolves: #330
- Added `decrease_position()` logic
- Added support for `Default::default()` on i128
- Added mocked missing functions 
Test can't be handled due to logic function missing.
=> Feat: implement decrease_position()

scripts/deploy_data_store_contract.sh, scripts/deploy_deposit_vault_contract.sh, scripts/deploy_event_emitter_contract.sh, scripts/deploy_fee_handler_contract.sh, scripts/deploy_oracle_contract.sh, scripts/deploy_oracle_store_contract.sh, scripts/deploy_order_vault_contract.sh, scripts/deploy_swap_handler_contract.sh
- Feature
Resolves: #NA
- added new deployment scripts
No
=> Added new deployment scripts

src/data/keys.cairo, src/fee/fee_utils.cairo, src/market/error.cairo, src/market/market_utils.cairo, tests/exchange/test_withdrawal_handler.cairo, tests/fee/test_fee_handler.cairo, tests/fee/test_fee_utils.cairo
- Feature
- Implemented claim_fees and claim_ui_fees functions
No
=> implemented claim_fees and claim_ui_fees functions

src/bank/strict_bank.cairo, src/order/order_vault.cairo, tests/order/test_order_vault.cairo
- Feature
Implemented order_vault, its using strict_bank functions so they need to be implemented in order to allow testing.
=> feat: implement order_vault & placeholder for test

src/event/event_emitter.cairo, src/lib.cairo, src/market/market_utils.cairo, src/order/order.cairo, src/position/decrease_position_collateral_utils.cairo, src/position/error.cairo, src/position/position_utils.cairo, src/pricing/position_pricing_utils.cairo, src/utils/default.cairo, tests/data/test_position.cairo, tests/event/test_market_events_emitted.cairo, tests/market/test_market_utils.cairo, tests/position/test_decrease_position_collateral_utils.cairo, tests/position/test_position_utils.cairo
- Feature
- Testing
Resolves: #328 
Implemented `decrease_position_collateral_utils` and basic tests.
=> feat: implement decrease_position_collateral_utils

src/mock/error.cairo, src/mock/governable.cairo, src/mock/referral_storage.cairo, tests/mock/test_referral_storage.cairo
- Testing
Resolves: #482 
- Added unit tests for every functions of `referral_storage` into `tests/mock/test_referral_storage.cairo`
No
=> test: Improve tests for referral_storage contract

src/deposit/error.cairo, src/deposit/execute_deposit_utils.cairo, src/event/event_utils.cairo, src/order/increase_order_utils.cairo, src/pricing/swap_pricing_utils.cairo, src/reader/reader_pricing_utils.cairo, src/swap/error.cairo
- Feature
Resolves: #354
- Implement the `execute_deposit` function in the `execute_deposit_utils` library.
- Implement the `_execute_deposit` function in the `execute_deposit_utils` library.
- Implement the `swap` function in the `execute_deposit_utils` library.
No
Still working on adding some basic unit test
=> ✨ execute_deposit_utils functions

.all-contributorsrc, README.md
Adding of :
-dic0de : https://github.com/keep-starknet-strange/satoru/commits?author=dic0de
-akhercha : https://github.com/keep-starknet-strange/satoru/commits?author=akhercha
-VictorONN : https://github.com/keep-starknet-strange/satoru/commits?author=VictorONN
-kasteph : https://github.com/keep-starknet-strange/satoru/commits?author=kasteph
=> add new contributors

src/data/data_store.cairo, src/router/error.cairo, src/router/exchange_router.cairo
- Feature
Resolves: #NA
- Implemented exchange_router contract
No
=> Feat: Implemented exchange_router contract

scripts/bank/deploy_StrictBank_contract.sh, scripts/bank/deploy_bank_contract.sh, scripts/config/deploy_config_contract.sh, scripts/config/deploy_timelock_contract.sh, scripts/data/deploy_data_store_contract.sh, scripts/deposit/deploy_deposit_vault_contract.sh, scripts/event/deploy_event_emitter_contract.sh, scripts/exchange/deploy_adl_handler_contract.sh, scripts/exchange/deploy_base_order_handler_contract.sh, scripts/exchange/deploy_deposit_handler_contract.sh, scripts/exchange/deploy_liquidation_handler_contract.sh, scripts/exchange/deploy_order_handler_contract.sh, scripts/exchange/deploy_withdrawal_handler_contract.sh, scripts/fee/deploy_fee_handler_contract.sh, scripts/market/deploy_market_factory_contract.sh, scripts/market/deploy_market_token_contract.sh, scripts/mock/deploy_governable_contract.sh, scripts/mock/deploy_referral_storage.sh, scripts/oracle/deploy_oracle_contract.sh, scripts/oracle/deploy_oracle_store_contract.sh, scripts/oracle/deploy_price_feed_contract.sh, scripts/order/deploy_order_vault_contract.sh, scripts/reader/deploy_reader_contract.sh, scripts/role/deploy_role_module_contract.sh, scripts/role/deploy_role_store_contract.sh, scripts/router/deploy_exchange_router_contract.sh, scripts/router/deploy_router_contract.sh, scripts/swap/deploy_swap_handler_contract.sh, scripts/withdrawal/deploy_withdrawal_vault_contract.sh
- Feature
Resolves: #NA
-Improved Deployement Scripts by adding flags to the commands
No
=> Deployment: Improved Deployement Scripts

book/src/README.md, book/src/continuous-integration/README.md, book/src/smart-contracts-architecture/data-module.md, src/event/event_emitter.cairo, src/exchange/adl_handler.cairo, src/exchange/base_order_handler.cairo
=> Fix: typos

.devcontainer/devcontainer.json, book/src/getting-started/prerequisites.md
- Other (please describe): dev tools
Resolves: #NA
- add devcontainer settings
No
=> dev: Add devcontainer

scripts/swap/deploy_swap_handler_contract.sh, src/bank/bank.cairo, src/data/data_store.cairo, src/swap/swap_handler.cairo, src/tests_lib.cairo, tests/exchange/test_liquidation_handler.cairo, tests/position/test_decrease_position_swap_utils.cairo, tests/position/test_decrease_position_utils.cairo, tests/swap/test_swap_handler.cairo
- Feature
Resolves: #NA
- added Global Reentrency in swap_handler contract
No
=> Global reentrency swap_handler

Scarb.toml, src/event/event_emitter.cairo, tests/adl/test_adl_utils.cairo, tests/bank/test_bank.cairo, tests/event/test_adl_events_emitted.cairo, tests/event/test_callback_events_emitted.cairo, tests/event/test_config_events_emitted.cairo, tests/event/test_gas_events_emitted.cairo, tests/event/test_market_events_emitted.cairo, tests/event/test_oracle_events_emitted.cairo, tests/event/test_order_events_emitted.cairo, tests/event/test_position_events_emitted.cairo, tests/event/test_pricing_events_emitted.cairo, tests/event/test_referral_events_emitted.cairo, tests/event/test_swap_events_emitted.cairo, tests/event/test_timelock_events_emitted.cairo, tests/event/test_withdrawal_events_emitted.cairo, tests/exchange/test_deposit_handler.cairo, tests/exchange/test_liquidation_handler.cairo, tests/exchange/test_withdrawal_handler.cairo, tests/market/test_market_factory.cairo, tests/market/test_market_token.cairo, tests/referral/test_referral_utils.cairo
- Testing
Tests are currently failing with new version of `starknet-foundry`.
- I've started working from @zarboq [pull request](https://github.com/keep-starknet-strange/satoru/pull/521) branch from commit #[36ca00248148a7b6397378bf860a7884253fc66b](https://github.com/keep-starknet-strange/satoru/pull/521/commits/36ca00248148a7b6397378bf860a7884253fc66b).
I've changed all the unit tests that were still failing; now when doing `snforge` on the repo it works! 🎉
- I've also completed some TODOS for the renaming of some events now that we don't call them using felts.
No
Then if we only merge this PR the tests won't all work, it needs to be combined with @zarboq 's one.
=> tests: Fix event tests for snforge 0.8+

src/deposit/deposit_vault.cairo
- Feature
Resolves: #NA
- Added missing functions deposit_vault
No
=> Added missing functions deposit_vault

.devcontainer/devcontainer.json
- Other (please describe): Dev tool
Resolves: #NA
- Since #524, we can use `starknet-foundry` v 0.8+
No
=> dev: Update starknet-foundry to 0.8.2 in devcontainer.json

tests/exchange/test_deposit_handler.cairo
- Bugfix
The constructor arguments are inverted for `DepositVault`.
Resolves: #NA
- Use `data_store_address` has first argument, and `role_store_address` has second argument.
-
-
=> Fix contructor args order

book/src/smart-contracts-architecture/oracle-module.md
Satoru book, Oracle module section, Incorrect formula for calculating token amount.
Resolves: #NA
Satoru book, Fix Oracle module section
No
=> Fix Satoru book oracle module description

.devcontainer/devcontainer.json, .github/workflows/test.yml, Scarb.toml, book/src/continuous-integration/workflows.md
- Feature
- Testing
snforge 0.8.2, crashing
snforge v0.8.3 working fixing memory issues
=> feat: use snforge v0.8.3

src/utils/calc.cairo, tests/pricing/test_swap_pricing_utils.cairo
- Bugfix
- Testing
- fixed tests swap_pricing_utils
No
=> fix_tests: swap_pricing_utils

src/adl/adl_utils.cairo, src/data/data_store.cairo, src/deposit/deposit_utils.cairo, src/deposit/execute_deposit_utils.cairo, src/exchange/base_order_handler.cairo, src/exchange/deposit_handler.cairo, src/exchange/order_handler.cairo, src/exchange/withdrawal_handler.cairo, src/liquidation/liquidation_utils.cairo, src/market/market_store_utils.cairo, src/market/market_utils.cairo, src/order/decrease_order_utils.cairo, src/order/increase_order_utils.cairo, src/reader/reader.cairo, src/reader/reader_utils.cairo, src/router/exchange_router.cairo, src/withdrawal/withdrawal_utils.cairo, tests/adl/test_adl_utils.cairo, tests/data/test_deposit_store.cairo, tests/data/test_market.cairo, tests/data/test_order.cairo, tests/data/test_position.cairo, tests/data/test_withdrawal.cairo, tests/exchange/test_base_order_handler.cairo, tests/exchange/test_liquidation_handler.cairo, tests/exchange/test_withdrawal_handler.cairo, tests/market/test_market_factory.cairo, tests/market/test_market_utils.cairo
- Feature
Resolves: #532 
-
-
-
Yes, functions to get `Order`, `Deposit`, `Withdrawal`, `Market` and `Position` return an empty struct.
=> feat: modify data_store behavior when getting structs

src/adl/adl_utils.cairo, src/deposit/execute_deposit_utils.cairo, src/market/market_utils.cairo, src/reader/reader.cairo, src/withdrawal/withdrawal_utils.cairo, tests/exchange/test_withdrawal_handler.cairo, tests/referral/test_referral_utils.cairo
- Bugfix
- Feature
- Add missing function and fix functions in market_utils.cairo
No
=> fix and add missing market_utils functions

src/order/decrease_order_utils.cairo, src/order/swap_order_utils.cairo, src/position/decrease_position_swap_utils.cairo, src/position/decrease_position_utils.cairo
- Bugfix
- fixed bugs in order and position utils files
No
=> fix: order/position utils files

book/src/smart-contracts-architecture/position-module.md
=> fix error in book

src/deposit/execute_deposit_utils.cairo, src/market/market_token.cairo, src/position/decrease_position_utils.cairo, src/reader/reader_utils.cairo, src/swap/swap_utils.cairo
- Bugfix
- fix to_signed() with correct sign
No
=> fix to_signed() with correct sign

src/deposit/execute_deposit_utils.cairo
- Bugfix
- fix i128 implementation in execute_deposit_utils
No
=> fix: execute_deposit_utils

.github/workflows/security.yml
Fix semgrep issues on CI by setting version to 1.45.0
=> fix: set semgrep version in CI to 1.45.0

.github/workflows/security.yml, README.md
=> fix: typo readme

src/market/error.cairo
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
=> already defined variable

src/adl/adl_utils.cairo, src/data/data_store.cairo, src/feature/feature_utils.cairo, src/market/market_utils.cairo, src/reader/reader.cairo, src/swap/swap_utils.cairo, src/utils/global_reentrancy_guard.cairo, tests/data/test_data_store.cairo, tests/utils/test_reentrancy_guard.cairo
- Bugfix
- remove option return value on get_bool
No
=> fix option return value in data_store.cairo

src/adl/error.cairo, src/order/error.cairo
correct the variable name `POSTION_NOT_VALID` to `POSITION_NOT_VALID` , which will correspond to description in [docs](https://github.com/keep-starknet-strange/satoru/tree/main/book/src/smart-contracts-architecture/adl-module.md)
=> fix: correct the variable name

src/market/market_utils.cairo, src/position/position_utils.cairo, tests/position/test_position_utils.cairo
- Testing
- Other: Refactoring of the update_open_interest() function
The testing module position_utils should be improved.
New tests implemented, and they are all passing. The tests implemented are the following:
- test_is_position_liquiditable_below_min_collateral_leverage
- test_is_position_liquiditable_valid_position
- test_is_position_liquiditable_below_min_collateral
- test_is_position_liquiditable_negative_remaining_collateral_usd
- test_update_open_interest
- test_handle_referral
- test_update_total_borrowing
Testing is still needed to be done on the following functions: 
- will_collateral_be_sufficient()
- update_funding_and_borrowing_state()
=> Improve tests of position_utils library.

src/deposit/execute_deposit_utils.cairo, src/event/event_emitter.cairo, src/event/event_utils.cairo, src/oracle/oracle_modules.cairo, src/order/base_order_utils.cairo, src/order/decrease_order_utils.cairo, src/order/increase_order_utils.cairo, src/order/order_utils.cairo, src/order/swap_order_utils.cairo, src/position/decrease_position_collateral_utils.cairo, src/position/decrease_position_swap_utils.cairo, src/price/price.cairo, src/referral/referral_utils.cairo, src/role/role_store.cairo, src/utils/i128.cairo, src/utils/span32.cairo, src/utils/starknet_utils.cairo, src/utils/traits.cairo, src/withdrawal/withdrawal_utils.cairo
- Feature
- removed inlines
No
=> feat: Remove all inlines

src/utils/serializable_dict.cairo, tests/utils/test_serializable_dict.cairo
- Testing
Resolves: #NA
- Added tests for SerializableDict to check if we can easily compare Items (single & spans).
No
@Sk8erboi84
=> tests: Added tests for SerializableFelt252Dict

.all-contributorsrc, README.md
:busts_in_silhouette: Add @faytey as a contributor
=> :busts_in_silhouette: Add @faytey as a contributor

src/oracle/oracle_store.cairo
- Feature
Resolves: #583 
implemented oracle_store
=> feat: implement `oracle_store`

tests/integration/create_market.cairo
- Testing
- Implemented test that add liquidity with unauthorized address then failed
No
=> Integration Test:  Add Liquidity with unauthorized address

tests/position/test_position_utils.cairo
add test_will_position_collateral_be_sufficient for testing
- Feature
Resolves: #567 
test fine.
No
test_update_funding_and_borrowing_state not implemented yet, will provide in a separate PR
=> feat: add test_will_position_collateral_be_sufficient

src/deposit/execute_deposit_utils.cairo
- Bugfix
- fix execute_deposit_utils
No
=> fix: fix execute_deposit_utils

src/deposit/execute_deposit_utils.cairo, src/exchange/order_handler.cairo, src/oracle/oracle.cairo, src/order/order_utils.cairo, src/order/swap_order_utils.cairo, src/swap/swap_utils.cairo, tests/integration/create_market.cairo, tests/integration/swap_test.cairo, tests/lib.cairo
=> Added swap test and fixed the bug where we would get x2 the amount

src/withdrawal/withdrawal_utils.cairo, tests/integration/create_market.cairo
- Testing
- Testing withdrawal (creation in datastore)
No
=> Test/ added withdrawal creation

src/exchange/withdrawal_handler.cairo, src/market/market_utils.cairo, src/swap/swap_utils.cairo, src/withdrawal/withdrawal_utils.cairo, tests/integration/create_market.cairo
- Bugfix
- Testing
- Deposit and withdrawal passing integration test
No
=> Test/ Deposit and withdrawal passing integration test

scripts/app/deployApp.ts, scripts/app/testDeploy.ts, src/exchange/adl_handler.cairo, src/exchange/base_order_handler.cairo, src/exchange/liquidation_handler.cairo, src/exchange/order_handler.cairo, src/lib.cairo, src/order/decrease_order_utils.cairo, src/order/increase_order_utils.cairo, src/order/order_utils.cairo, src/order/swap_order_utils.cairo, src/position/decrease_position_utils.cairo, tests/integration/swap_test.cairo, tests/integration/test_deposit_withdrawal.cairo, tests/integration/test_long_integration.cairo, tests/integration/test_short_integration.cairo, tests/lib.cairo
OrderHandler contract is too big to be deployed
Changing some of its dependencies to independent contracts to reduce its size.
=> Feat: decrease order handler size

scripts/app/deployApp.ts
=> feat: deploy exchange router

scripts/app/deployApp.ts
Fix arguments in script constructors
=> feat: update deployment script

scripts/app/deployApp.ts
Add controller role to exchangeRouter
=> feat: add controller role to exchangeRouter

src/order/order_utils.cairo, src/withdrawal/withdrawal_utils.cairo
- Bugfix
Key field is set after event emission
Set field before emitting event
=> fix: fix key field in Order and Withdrawal
