keep-starknet-strange/satoru

src/data/data_store.cairo
tests/data/test_data_store.cairo

Implemented i128 data type at src/data/data_store
Currently using u128 as Serde and Store implementation for i128 has not been released yet.
**Issue created for updating u128 to i128 when Serde and Store for i128 is released:**
https://github.com/keep-starknet-strange/satoru/issues/257
- Feature
Resolves: #59
- data_store , get , remove, increment and decrement for i128
No
None

Feat: i128 data implementation on data/data_store

---

Scarb.toml
src/oracle/oracle.cairo
src/utils/error.cairo
src/utils/u128_mask.cairo
tests/utils/test_u128_mask.cairo

Implements the `fn validate_unique_and_set_index(mask: u128, index: u128, label: felt252)` in the u128Mask library
Note: This differs a bit from the GMX implementation, we use a 128-bits wide mask only.
The initial implementation states:
```rust
// since minPrices, maxPrices have the same length as the signers array
// and the signers array length is less than MAX_SIGNERS
// minPriceIndexMask and maxPriceIndexMask should be able to store the indexes
// using Uint256Mask
```
And `MAX_SIGNERS =  256 / SIGNER_INDEX_LENGTH - 1;` where `SIGNER_INDEX_LENGTH = 16;` so it should fit in 128 bits anyways
- Bugfix
- …

feat: u128 mask

---

src/adl/adl_utils.cairo
src/exchange/adl_handler.cairo
src/exchange/base_order_handler.cairo
src/lib.cairo
src/market/market_utils.cairo
src/oracle/oracle_utils.cairo
src/order/order.cairo
src/order/order_utils.cairo

- Feature
Closes: #275
No
Temporarily made `fn get_execute_order_params()` public in `base_order_handler.cairo`. Open to alternatives for closer alignment with Solidity.
**EDIT**
The issue mentioned in the additional details has been resolved.

Add Implementation for adl_handler Functions

---

src/lib.cairo
src/utils/starknet_utils.cairo
tests/utils/test_starknet_utils.cairo

https://github.com/keep-starknet-strange/satoru/issues/348
Added gasprice and gasleft mock methods, which return the value provided. These can be used implementing [GasUtils.sol](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/gas/GasUtils.sol). 
For future starknet upgrades, we can simply modify these methods instead of all gas calls.
- Feature
Resolves: #NA
-
-
-

feat: mock gas utils

---

.vscode/settings.json
src/lib.cairo
src/order/base_order_utils.cairo
src/tests/utils/test_i128.cairo

Adding missing operations on i128:
- div
- mul
- storage (and thus serde)
- Feature
Resolves: #406 
Should now be possible to divide, multiply and store i128
No
It probably isn't the most efficient way, but this **SHOULD** be deleted once we upgrade the Cairo compiler version to a version that supports operations on i128 (prob 2.3.0)

Feat/i128 operations (div, mul, storage, serde)

---

src/bank/strict_bank.cairo
src/deposit/deposit.cairo
src/deposit/deposit_utils.cairo
src/deposit/deposit_vault.cairo
src/deposit/error.cairo
src/event/event_emitter.cairo
src/gas/error.cairo
src/gas/gas_utils.cairo
src/lib.cairo
src/order/order.cairo
src/order/order_vault.cairo
src/tests/data/test_order.cairo
src/tests/deposit/test_deposit_utils.cairo
src/tests/event/test_withdrawal_events_emitted.cairo
src/withdrawal/withdrawal.cairo
src/withdrawal/withdrawal_utils.cairo

- Feature deposit_utils
Resolves: https://github.com/keep-starknet-strange/satoru/issues/353
- create_deposit and cancel_deposit are implemented for now without test. Waiting for next foundry version.
- Update deposit struct to use u128 and u64 for updated_at_block
- Update gas_utils::validate_execution_fee to use u128
- Add new function gas_utils::pay_execution_fee_deposit similiar to gas_utils::pay_execution_fee but taking as parameter IDepositVaultDispatcher
- Contract class for tests created but need next foundry version to simulate call to record_transfer_in,validate_callback_gas_limit,transfer_out

Feat:Implement deposit_utils

---

src/data/data_store.cairo
src/oracle/oracle.cairo
src/oracle/price_feed.cairo
src/tests/exchange/test_liquidation_handler.cairo
src/tests/exchange/test_withdrawal_handler.cairo
src/tests/oracle/test_oracle.cairo
src/tests/swap/test_swap_handler.cairo
src/tests_lib.cairo

The `Oracle` contract now supports Pragma oracle integration. Added a new `pragma_address` constructor argument and `price_feed` storage variable for the updated `IPriceFeed` dispatcher.
To make this possible, `DataStore` has been extended with two new methods: `set_token_id` and `get_token_id`. A new storage map `tokens_ids: LegacyMap::<ContractAddress, felt252>` is also introduced.
Test suite has been updated accordingly.

Feat: Integration with Pragma Oracle

---

src/adl/adl_utils.cairo
src/data/keys.cairo
src/deposit/deposit_utils.cairo
src/event/event_emitter.cairo
src/exchange/order_handler.cairo
src/gas/error.cairo
src/order/base_order_utils.cairo
src/order/order.cairo
src/position/decrease_position_swap_utils.cairo
src/router/exchange_router.cairo
src/swap/swap_utils.cairo
src/tests/data/test_keys.cairo
src/tests/data/test_order.cairo
src/tests/data/test_withdrawal.cairo
src/tests/deposit/test_deposit_utils.cairo
src/tests/event/test_callback_events_emitted.cairo
src/tests/event/test_order_events_emitted.cairo
src/tests/event/test_withdrawal_events_emitted.cairo
src/tests/exchange/test_withdrawal_handler.cairo
src/tests/order/test_order.cairo
src/tests/position/test_decrease_position_swap_utils.cairo
src/tests/swap/test_swap_handler.cairo
src/token/token_utils.cairo
src/withdrawal/error.cairo
src/withdrawal/withdrawal.cairo
src/withdrawal/withdrawal_utils.cairo
src/withdrawal/withdrawal_vault.cairo

Since we are considering ETH erc20 to be the equivalent of "native token", it's probably a good idea to correct the terminology used throughout the code base.
Wrapped native token terminology used
Resolves: #442 
Terminology refactored to `fee_token`
No. It does however begin to differ from the gmx-synthetics repo

dev: refactor wnt to fee_token

---

src/role/role_store.cairo
src/tests/role/test_role_store.cairo

Implemented `role_store` and added corresponding tests.
Resolves: #432 
The new implementation mimics the behavior of the Solidity version but avoids using arrays in storage. Instead, `role_members_count` and `roles_count` track the total number of writes rather than the actual instance count. This is because deleting a `<key, value>` pair sets the `value` to `zero()` rather than removing it. To manage storage efficiently, the algorithm checks existing keys from 0 to the current storage count during insertion. If a `zero()` value is found, that key is reused; otherwise, a new key-value pair is created and the key count is incremented.
None.
N/A

Feat: Completed Implementation of `role_store` contract. 

---

src/role/error.cairo
src/role/role_store.cairo
tests/role/test_role_store.cairo

The `role_store.cairo` code allows for granting and revoking of roles. The only role allowed to do this, is the `ROLE_ADMIN`, therefore it is important that if the contract has only a single account of role `ROLE_ADMIN` then it should not be that the role is revoked, because:
1. The `_revoke_role` removes the role from roles if there is no members as seen here
``` cairo
if self.get_role_member_count(role_key).is_zero() {
let role_index = self._find_role_index(role_key);
self.roles.write(role_index, Zeroable::zero());
}
```
Meaning, that if we only have a single account as `ROLE_ADMIN` and revoke, it then, that role would be deleted and therefore future granting and revocation of roles would not be possible hence any future change is not possible.
With the aforementioned issue, I recommend …

Adding Role admin check to the role-admin branch

---

src/deposit/deposit_vault.cairo
tests/deposit/test_deposit_vault.cairo

- Testing
Resolves: Issue [#477 ](https://github.com/keep-starknet-strange/satoru/issues/477)
- Swapped the order of constructor parameters for `DepositVault` so it's the same order as `StrictBank` & follows the `initialize()` function order
- Added unit tests into `test/deposit/deposit_vault.cairo`
Should be a **no**, but there is that swap of parameters order in the `DepositVault` constructor. I can revert it if it's dangerous/out of scope!
1. I have no implemented tests for `record_transfer_in()` as the function is not implemented yet. Happy to do it in this PR if you have more informations! 😁
2. I've this test that should fail:
```rust
#[test]
#[should_panic(expected: ('u256_sub Overflow',))]
fn …
```

test: Tests for deposit_vault

---

src/bank/strict_bank.cairo
src/deposit/deposit_vault.cairo
tests/deposit/test_deposit_vault.cairo

- Feature
- Testing
Resolves: #497 
- Added implementation of `deposit_vault::record_transfer_in`
- Added related unit tests
No
The function `StrictBank::record_transfer_in_internal` used to overflow & panic when the new balance was lower than the previous one recorded. A check has been added, it now returns zero if its is lower.
Let me know if it should panic as before instead!

test: Added tests for record_transfer_in

---

tests/mock/test_governable.cairo

Resolution of #481 
-add comments to all tests
-Addition of a test to test the error case of the `transfer_ownership` function.
-Addition of a test to test the `accept_ownership` function.
-Addition of a test tot test the error case of the `accept_ownership` function.
-Addition of a test tot test the error case of the `initialize` function.
Enjoy the review ;)

Improve tests of governable contract

---

src/order/base_order_utils.cairo
src/order/error.cairo
tests/order/test_base_order_utils.cairo

test: Improve tests of base_order_utils

---

.github/workflows/test.yml
src/exchange/withdrawal_handler.cairo
src/role/role_store.cairo
src/swap/swap_handler.cairo
src/tests_lib.cairo
tests/bank/test_strict_bank.cairo
tests/config/test_config.cairo
tests/data/test_deposit_store.cairo
tests/data/test_market.cairo
tests/data/test_withdrawal.cairo
tests/deposit/test_deposit_utils.cairo
tests/exchange/test_base_order_handler.cairo
tests/exchange/test_deposit_handler.cairo
tests/fee/test_fee_handler.cairo
tests/fee/test_fee_utils.cairo
tests/market/test_market_utils.cairo
tests/mock/test_governable.cairo
tests/mock/test_referral_storage.cairo
tests/oracle/test_oracle.cairo
tests/order/test_base_order_utils.cairo
tests/position/test_decrease_position_swap_utils.cairo
tests/position/test_decrease_position_utils.cairo
tests/pricing/test_position_pricing_utils.cairo
tests/role/test_role_module.cairo
tests/role/test_role_store.cairo
tests/router/test_router.cairo
tests/swap/test_swap_handler.cairo

- Bugfix
- Feature
- Testing
Starknet foundry version 0.8.0 modified the way the internal caller address is computed so it broke our tests.
Resolves: #NA
I deploy contracts at a specific address and `start_prank(specified_address, caller_address)` before deploy so the deployer remains our caller address.

feat: fix test for snforge 0.8.0

---

src/data/data_store.cairo

- Bugfix
If the index isn't found in `remove_*` function, then `offsetted_index == 0` and panic with `u32_sub Overflow` in the instruction `let index = offsetted_index - 1;`.
If the index isn't found in `remove_*` function, then `offsetted_index == 0` and panic with `MarketError::MARKET_NOT_FOUND`.
No

fix: `u32_sub Overflow` if the index isn't found in datastore

---

src/exchange/withdrawal_handler.cairo
src/market/market_utils.cairo
src/withdrawal/withdrawal_utils.cairo
tests/exchange/test_withdrawal_handler.cairo

- Testing
Resolves: https://github.com/keep-starknet-strange/satoru/issues/480
- Tests improved for create and cancel withdrawal
No
Tests list for create and cancel withdrawal :
- given_normal_conditions_when_create_withdrawal_then_works
- given_market_token_amount_equal_zero_when_create_withdrawal_then_fails
- given_fee_token_lower_than_execution_fee_conditions_when_create_withdrawal_then_fails
- given_caller_not_controller_when_create_withdrawal_then_fails
- given_normal_conditions_when_cancel_withdrawal_then_works
- given_unexisting_key_when_cancel_withdrawal_then_fails
- given_account_address_zero_when_cancel_withdrawal_then_fails
- given_market_token_equals_zero_when_cancel_withdrawal_then_fails
- …

Improve test widthdrawal handler

---

.github/workflows/test.yml

`SCARB_VERSION` remained unused, could be a source of confusion if someone changed it expecting different scarb version to be used

Use SCARB_VERSION in CI

---

tests/swap/test_swap_handler.cairo

This PR is with respect to this issue #493 
- Testing
Given normal conditions, all tests are passing. 
Below are my findings : 
1. https://github.com/keep-starknet-strange/satoru/blob/e665cfeca0b29879417dded83127ea583dd2af5c/src/swap/swap_utils.cairo#L291 
when this condition (_params.receiver != _params.market.market_token) in the if statement block is being satisfied, it returns [input to long for argument] error.
2. https://github.com/keep-starknet-strange/satoru/blob/e665cfeca0b29879417dded83127ea583dd2af5c/src/swap/swap_utils.cairo#L183 when this condition (_params.token_in != _params.market.long_token && _params.token_in != _params.market.short_token) in the if statement block is being satisfied, program …

Added 3 unit tests, Refactored 1 test  in test_swap_handler.cairo

---

src/oracle/oracle_modules.cairo

- Bugfix
Resolves: #602 
- Loop through all `params.primary_tokens.len()` when run `with_simulated_oracle_prices_before function` in `oracle_modules.cairo`
No

Add increment of cur_idx in with_simulated_oracle_prices_before function

---

src/data/data_store.cairo
tests/data/test_deposit_store.cairo
tests/data/test_order.cairo
tests/data/test_position.cairo
tests/data/test_withdrawal.cairo

- Bugfix
- Testing
- List index out of bounds when remove last index element of deposit, withdrawal, order, position in Datastore
Resolves: #607 
- Able to remove last element of deposit, withdrawal, order, position in Datastore
No

Fix bug List index out of bounds when remove last index element in Datastore

---

.github/semgrep-cairo-rules.yaml
.github/workflows/security.yml

Currently, our CI workflow is using AVNU Semgrep rules.
Resolves: #455 
This PR integrates Avnu semgrep rules with new semgrep rules from https://github.com/keep-starknet-strange/satoru/pull/453 into our GitHub Actions CI workflow.
No. This change only affects the CI workflow and does not alter the application's functionality or API.

Update Semgrep Rules and Semgrep config path for CI

---

src/exchange/base_order_handler.cairo
src/exchange/liquidation_handler.cairo
src/exchange/order_handler.cairo
src/order/order_utils.cairo
tests/integration/swap_test.cairo
tests/integration/test_deposit_withdrawal.cairo
tests/integration/test_long_integration.cairo
tests/integration/test_short_integration.cairo

Use library calls in `BaseOrderHandler` in order to apply storage modifications to current contract and avoid different caller_address.

feat: use library calls

---

src/deposit/error.cairo
src/deposit/execute_deposit_utils.cairo
src/exchange/deposit_handler.cairo

Add value indication to deposit_pool_value error.

Fix: deposit pool value error
